services:
  - type: web
    name: pdf-schema-generator
    env: python
    plan: free
    branch: main
    buildCommand: bash ./build.sh
    startCommand: gunicorn config.wsgi --log-file -
    healthCheckPath: /api/health
